### ISSUE TITLE
Verify if asyncResult.Delay needs to delegate to async.Delay

### ISSUE THREAD

**Issue by danyx23** [cmeeren/Cvdm.ErrorHandling#13]
When investigating #11 I was wondering if asyncResult.Delay must also delegate to Delay to keep the cancellationtoken semantics etc of the async type. I'm not familiar enough with CEs, do you know if this might be necessary?

**Comment by cmeeren** [comment]
To be honest I don't really know. I have no deep understanding of what `Delay` does. If you want to investigate, then you're very welcome (I'll happily accept a PR with a unit test to verify correct behavior even if it's currently green).

**Comment by danyx23** [comment]
Ok cool, I'll have a look, I think this is the one case that looks like a potential problem. I'll report back when I know more (might take a few days though as I am travelling atm)

**Comment by cmeeren** [comment]
Thanks, no hurry.

**Comment by cmeeren** [comment]
@danyx23 Did you have a look at it?

**Comment by danyx23** [comment]
@cmeeren yes I tried to get the unit tests from the FSharp.Core git repo regarding async to work with a drop in replacement of asyncResult but I ran into several problems with that approach. I also tried to delegate this to async.Delay but ran into some strange type errors then. I would like to revisit this at some point because we are using asyncResult quite a bit now but don't have much time for this at the moment. If you like you can close the issue for now and I will reopen it when I come back to investigating it (or if you don't mind of course we can leave this issue open)

**Comment by cmeeren** [comment]
Thanks for your efforts. I'll leave this open.

**Comment by cmeeren** [comment]
I've rewritten the CEs for v2.0.0, and delegated to `async` as much as possible. Closing this,
